# Generated by Django 5.0.7 on 2024-07-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.CharField(choices=[('wood', 'Wood Related'), ('printing', '3D Printing'), ('electronics', 'Electronics'), ('others', 'Others')], max_length=50)),
            ],
        ),
    ]
